Console.Clear();
Console.WriteLine("Введите семь чисел для нахождения их среднего армифметического: ");
Console.Write("Введите первое число: ");
double n1 = Convert.ToInt32(Console.ReadLine());
Console.Write("Введите второе число: ");
double n2 = Convert.ToInt32(Console.ReadLine());
Console.Write("Введите третье число: ");
double n3 = Convert.ToInt32(Console.ReadLine());
Console.Write("Введите четвёртое число: ");
double n4 = Convert.ToInt32(Console.ReadLine());
Console.Write("Введите пятое число: ");
double n5 = Convert.ToInt32(Console.ReadLine());
Console.Write("Введите шестое число: ");
double n6 = Convert.ToInt32(Console.ReadLine());
Console.Write("Введите седьмое число: ");
double n7 = Convert.ToInt32(Console.ReadLine());
double sum = 0;
double mean = 0;
sum = n1 + n2 + n3 + n4 + n5 + n6 + n7;
mean = sum / 7;
Console.Write("Среднее арифметическое введённых чисел = " + mean);